### ISSUE TITLE
How to handle camel-jcifs consumer exception by camel onexception handler

### ISSUE THREAD

**Issue by muthumani-prabhu** [camel-extra/camel-extra#24]
Could you please guide on how to handle camel-jcifs consumer exception? I tried the following route

from("smb://xxxxxxx/&noop=true&idempotent=true&delay=10000&readLock=changed&readLockCheckInterval=5000&**consumer.bridgeErrorHandler**=true").onException(Exception.class).handled(true).process(new ErrorProcessor(sampleDocument));

Route worked fine for FTP/File component when the connection exception is thrown from consumer component. When I tried doing the same on jcifs, it is just displaying the connection exception as warning and not bridged with camel exception handler to be handled by onexception.

Exception as below
===============
2019-04-26T10:22:52.517+0530 WARN o.a.c.c.j.SmbConsumer-213 Consumer Consumer[smb:/xxxxxxx/&noop=true&idempotent=true&delay=10000&readLock=changed&readLockCheckInterval=5000&consumer.errorHandler=true] failed polling endpoint: smb:/xxxxxxxx/&noop=true&idempotent=true&delay=10000&readLock=changed&readLockCheckInterval=5000&consumer.errorHandler=true. Will try again at next poll. Caused by: [org.apache.camel.component.file.GenericFileOperationFailedException - Could not get files Failed to connect: 0.0.0.0<00>/10.96.59.177]
org.apache.camel.component.file.GenericFileOperationFailedException: Could not get files Failed to connect: 0.0.0.0<00>/10.96.59.177
	at org.apacheextras.camel.component.jcifs.SmbOperations.listFiles(SmbOperations.java:350) ~[camel-jcifs-2.22.0.jar!/:2.22.0]
	at org.apacheextras.camel.component.jcifs.SmbConsumer.pollDirectory(SmbConsumer.java:60) ~[camel-jcifs-2.22.0.jar!/:2.22.0]
	at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:128) ~[camel-core-2.23.0.jar!/:2.23.0]
	at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174) [camel-core-2.23.0.jar!/:2.23.0]
	at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101) [camel-core-2.23.0.jar!/:2.23.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/10.96.59.177
	at jcifs.smb.SmbTransport.connect(SmbTransport.java:309) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.connect(SmbFile.java:954) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.connect0(SmbFile.java:880) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.getType(SmbFile.java:1282) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.doEnum(SmbFile.java:1733) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1715) ~[jcifs-1.3.17.jar!/:?]
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1648) ~[jcifs-1.3.17.jar!/:?]
	at org.apacheextras.camel.component.jcifs.DefaultSmbClient.listFiles(DefaultSmbClient.java:161) ~[camel-jcifs-2.22.0.jar!/:2.22.0]
	at org.apacheextras.camel.component.jcifs.SmbOperations.listFiles(SmbOperations.java:346) ~[camel-jcifs-2.22.0.jar!/:2.22.0]

**Comment by muthumani-prabhu** [comment]
Apologies, it was my mistake, I failed to add "?" in the url
"smb://xxxxxxx/**?**noop=true&idempotent=true&delay=10000&readLock=changed&readLockCheckInterval=5000&consumer.bridgeErrorHandler=true
